// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/22/2024, 10:43:50 AM
const configMerger = require("C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/plugins/**/*.{js,ts,mjs}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/composables/**/*.{js,ts,mjs}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/utils/**/*.{js,ts,mjs}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "C:/Users/ayoku/Documents/GitHub/favour.cool/my-app_v2/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
